start python app_regras_stress.py
start python app_regras_stress.py
start python app_regras_stress.py
start python app_regras_stress.py
start python app_regras_stress.py
start python app_regras_stress.py
start python app_regras_stress.py
start python app_regras_stress.py
start python app_regras_stress.py
start python app_regras_stress.py
